# Generated by Django 5.1 on 2024-08-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_lesson_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name_plural': 'Доступ к продуктам'},
        ),
    ]
